services:
  database:
    container_name: api_rest_drf
    image: postgres:14.5-alpine
    restart: always
    volumes:
      - ./.pgdata:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=apirest
      - POSTGRES_USER=api
    ports:
      - 5434:5432