name: Aplicação Django

on: [pull_request]

jobs:
    build:

        runs-on: ubuntu-latest

        services:
          postgres:
            image: postgres:14.5
            env:
              POSTGRES_USER: test_user
              POSTGRES_PASSWORD: test_password
              POSTGRES_DB: test_db
            ports: [ '5432:5432' ]

        steps:
        - uses: actions/checkout@v3

        - name: Set up Python 3.10
          uses: actions/setup-python@v3
          with:
              python-version: '3.10'

        - name: Instalar Depencias
          run: |
              python -m pip install --upgrade pip
              pip install pip-tools
              pip-sync requirements.txt requirements-dev.txt

        - name: Verificando o estilo do codico com flake8
          run: |
              flake8

        - name: Copiando .env
          run: |
              cp contrib/env-sample .env


        - name: Rodar testes Automáticos
          run: |
              pytest
